const GENERATED_HEADER = "/* GENERATED by 98-System/99-dev/tools/build-styles.mjs. Do not edit this file. */";
const MOBILE_HEADER = "/* ObsidianCore mobile layout overrides.";
const MAX_BYTES = 512 * 1024;

const STYLE_FILES = Object.freeze([
  Object.freeze({
    id: "base",
    sourcePath: "98-System/90-config/styles/obsidian-core.css",
    targetName: "obsidian-core.css",
    managedHeader: GENERATED_HEADER,
  }),
  Object.freeze({
    id: "mobile",
    sourcePath: "98-System/90-config/styles/obsidian-core-mobile.css",
    targetName: "obsidian-core-mobile.css",
    managedHeader: MOBILE_HEADER,
  }),
]);

const SOURCE_PATH = STYLE_FILES[0].sourcePath;
const TARGET_NAME = STYLE_FILES[0].targetName;
const MOBILE_SOURCE_PATH = STYLE_FILES[1].sourcePath;
const MOBILE_TARGET_NAME = STYLE_FILES[1].targetName;

function safeVaultRelativePath(value, label) {
  if (typeof value !== "string") throw new Error(`${label} must be a string`);
  const normalized = value.replace(/\\/g, "/").replace(/\/+$/, "");
  if (!normalized || normalized.startsWith("/") || /^[A-Za-z]:/.test(normalized) || normalized.includes("\0")) {
    throw new Error(`${label} must be a safe relative Vault path`);
  }
  const parts = normalized.split("/");
  if (parts.some(part => !part || part === "." || part === "..")) {
    throw new Error(`${label} must not contain empty, dot, or parent segments`);
  }
  return normalized;
}

function asArrayBuffer(value, label) {
  if (value instanceof ArrayBuffer) return value.slice(0);
  if (ArrayBuffer.isView(value)) {
    return value.buffer.slice(value.byteOffset, value.byteOffset + value.byteLength);
  }
  throw new Error(`${label} must be binary data`);
}

function bytesEqual(left, right) {
  const a = new Uint8Array(asArrayBuffer(left, "left bytes"));
  const b = new Uint8Array(asArrayBuffer(right, "right bytes"));
  if (a.byteLength !== b.byteLength) return false;
  for (let index = 0; index < a.byteLength; index += 1) {
    if (a[index] !== b[index]) return false;
  }
  return true;
}

function beginsWithManagedHeader(data, header) {
  const bytes = new Uint8Array(asArrayBuffer(data, "style bytes"));
  const prefix = bytes.subarray(0, Math.min(bytes.byteLength, header.length + 32));
  return new TextDecoder("utf-8").decode(prefix).startsWith(header);
}

async function requireFile(adapter, path, label) {
  const stat = await adapter.stat(path);
  if (!stat || stat.type !== "file") throw new Error(`${label} must exist as a regular file: ${path}`);
  if (typeof stat.size === "number" && stat.size > MAX_BYTES) throw new Error(`${label} exceeds ${MAX_BYTES} bytes`);
  const bytes = asArrayBuffer(await adapter.readBinary(path), label);
  if (bytes.byteLength < 1 || bytes.byteLength > MAX_BYTES) throw new Error(`${label} has an invalid size`);
  return bytes;
}

async function inspectTarget(adapter, targetPath, desired, managedHeader, label) {
  const stat = await adapter.stat(targetPath);
  if (!stat) return { status: "created", current: null };
  if (stat.type !== "file") throw new Error(`${label} is not a file: ${targetPath}`);

  const current = await requireFile(adapter, targetPath, label);
  if (bytesEqual(current, desired)) return { status: "unchanged", current };
  if (!beginsWithManagedHeader(current, managedHeader)) {
    throw new Error(`Refusing to overwrite an unrecognized local file: ${targetPath}`);
  }
  return { status: "updated", current };
}

async function ensureFolder(adapter, path) {
  const before = await adapter.stat(path);
  if (before) {
    if (before.type !== "folder") throw new Error(`Core style target parent is not a folder: ${path}`);
    return false;
  }
  await adapter.mkdir(path);
  const after = await adapter.stat(path);
  if (!after || after.type !== "folder") throw new Error(`Core style target folder was not created: ${path}`);
  return true;
}

async function syncCoreStyle(tp, appOverride) {
  const appRef = appOverride ?? tp?.app ?? globalThis.app;
  const vault = appRef?.vault;
  const adapter = vault?.adapter;
  if (!vault || !adapter) throw new Error("Obsidian Vault adapter is required");

  const configDir = safeVaultRelativePath(vault.configDir, "Vault configDir");
  const targetDir = `${configDir}/snippets`;

  const desiredStyles = [];
  for (const style of STYLE_FILES) {
    const desired = await requireFile(adapter, style.sourcePath, `Core style distribution source (${style.id})`);
    if (!beginsWithManagedHeader(desired, style.managedHeader)) {
      throw new Error(`Core style distribution source is not recognized (${style.id})`);
    }
    desiredStyles.push({ ...style, desired, targetPath: `${targetDir}/${style.targetName}` });
  }

  const targetDirStat = await adapter.stat(targetDir);
  if (targetDirStat && targetDirStat.type !== "folder") {
    throw new Error(`Core style target parent is not a folder: ${targetDir}`);
  }

  const plans = [];
  for (const style of desiredStyles) {
    const inspection = targetDirStat
      ? await inspectTarget(adapter, style.targetPath, style.desired, style.managedHeader, `Core style target (${style.id})`)
      : { status: "created", current: null };
    plans.push({ ...style, ...inspection });
  }

  if (!targetDirStat) await ensureFolder(adapter, targetDir);

  const results = [];
  for (const plan of plans) {
    if (plan.status !== "unchanged") {
      await adapter.writeBinary(plan.targetPath, plan.desired);
      const written = await requireFile(adapter, plan.targetPath, `Core style target after write (${plan.id})`);
      if (!bytesEqual(written, plan.desired)) {
        throw new Error(`Core style target verification failed after write (${plan.id})`);
      }
    }
    results.push({
      id: plan.id,
      status: plan.status,
      sourcePath: plan.sourcePath,
      targetPath: plan.targetPath,
      bytes: plan.desired.byteLength,
    });
  }

  let status = "unchanged";
  if (results.some(result => result.status === "updated")) status = "updated";
  else if (results.some(result => result.status === "created")) status = "created";

  const base = results.find(result => result.id === "base");
  return {
    status,
    sourcePath: base.sourcePath,
    targetPath: base.targetPath,
    bytes: base.bytes,
    styles: results,
  };
}

module.exports = syncCoreStyle;
module.exports.SOURCE_PATH = SOURCE_PATH;
module.exports.TARGET_NAME = TARGET_NAME;
module.exports.MOBILE_SOURCE_PATH = MOBILE_SOURCE_PATH;
module.exports.MOBILE_TARGET_NAME = MOBILE_TARGET_NAME;
module.exports.GENERATED_HEADER = GENERATED_HEADER;
module.exports.MOBILE_HEADER = MOBILE_HEADER;
module.exports.STYLE_FILES = STYLE_FILES;
module.exports.safeVaultRelativePath = safeVaultRelativePath;
module.exports.bytesEqual = bytesEqual;
