const SOURCE_PATH = "98-System/90-config/styles/obsidian-core.css";
const TARGET_NAME = "obsidian-core.css";
const GENERATED_HEADER = "/* GENERATED by 98-System/99-dev/tools/build-styles.mjs. Do not edit this file. */";
const MAX_BYTES = 512 * 1024;

function safeVaultRelativePath(value, label) {
  if (typeof value !== "string") throw new Error(`${label} must be a string`);
  let normalized = value.replace(/\\/g, "/").replace(/\/+$/, "");
  if (!normalized || normalized.startsWith("/") || /^[A-Za-z]:/.test(normalized) || normalized.includes("\0")) {
    throw new Error(`${label} must be a safe relative Vault path`);
  }
  const parts = normalized.split("/");
  if (parts.some(part => !part || part === "." || part === "..")) {
    throw new Error(`${label} must not contain empty, dot, or parent segments`);
  }
  return normalized;
}

function asArrayBuffer(value, label) {
  if (value instanceof ArrayBuffer) return value.slice(0);
  if (ArrayBuffer.isView(value)) {
    return value.buffer.slice(value.byteOffset, value.byteOffset + value.byteLength);
  }
  throw new Error(`${label} must be binary data`);
}

function bytesEqual(left, right) {
  const a = new Uint8Array(asArrayBuffer(left, "left bytes"));
  const b = new Uint8Array(asArrayBuffer(right, "right bytes"));
  if (a.byteLength !== b.byteLength) return false;
  for (let index = 0; index < a.byteLength; index += 1) {
    if (a[index] !== b[index]) return false;
  }
  return true;
}

function beginsWithGeneratedHeader(data) {
  const bytes = new Uint8Array(asArrayBuffer(data, "style bytes"));
  const prefix = bytes.subarray(0, Math.min(bytes.byteLength, GENERATED_HEADER.length + 16));
  return new TextDecoder("utf-8").decode(prefix).startsWith(GENERATED_HEADER);
}

async function requireFile(adapter, path, label) {
  const stat = await adapter.stat(path);
  if (!stat || stat.type !== "file") throw new Error(`${label} must exist as a regular file: ${path}`);
  if (typeof stat.size === "number" && stat.size > MAX_BYTES) throw new Error(`${label} exceeds ${MAX_BYTES} bytes`);
  const bytes = asArrayBuffer(await adapter.readBinary(path), label);
  if (bytes.byteLength < 1 || bytes.byteLength > MAX_BYTES) throw new Error(`${label} has an invalid size`);
  return bytes;
}

async function ensureFolder(adapter, path) {
  const before = await adapter.stat(path);
  if (before) {
    if (before.type !== "folder") throw new Error(`Core style target parent is not a folder: ${path}`);
    return;
  }
  await adapter.mkdir(path);
  const after = await adapter.stat(path);
  if (!after || after.type !== "folder") throw new Error(`Core style target folder was not created: ${path}`);
}

async function syncCoreStyle(tp, appOverride) {
  const appRef = appOverride ?? tp?.app ?? globalThis.app;
  const vault = appRef?.vault;
  const adapter = vault?.adapter;
  if (!vault || !adapter) throw new Error("Obsidian Vault adapter is required");

  const configDir = safeVaultRelativePath(vault.configDir, "Vault configDir");
  const targetDir = `${configDir}/snippets`;
  const targetPath = `${targetDir}/${TARGET_NAME}`;

  const desired = await requireFile(adapter, SOURCE_PATH, "Core style distribution source");
  if (!beginsWithGeneratedHeader(desired)) throw new Error("Core style distribution source is not a generated bundle");

  await ensureFolder(adapter, targetDir);
  const targetStat = await adapter.stat(targetPath);
  let status = "created";

  if (targetStat) {
    if (targetStat.type !== "file") throw new Error(`Core style target is not a file: ${targetPath}`);
    const current = await requireFile(adapter, targetPath, "Core style target");
    if (bytesEqual(current, desired)) {
      return { status: "unchanged", sourcePath: SOURCE_PATH, targetPath, bytes: desired.byteLength };
    }
    if (!beginsWithGeneratedHeader(current)) {
      throw new Error(`Refusing to overwrite an unrecognized local file: ${targetPath}`);
    }
    status = "updated";
  }

  await adapter.writeBinary(targetPath, desired);
  const written = await requireFile(adapter, targetPath, "Core style target after write");
  if (!bytesEqual(written, desired)) throw new Error("Core style target verification failed after write");

  return { status, sourcePath: SOURCE_PATH, targetPath, bytes: desired.byteLength };
}

module.exports = syncCoreStyle;
module.exports.SOURCE_PATH = SOURCE_PATH;
module.exports.TARGET_NAME = TARGET_NAME;
module.exports.GENERATED_HEADER = GENERATED_HEADER;
module.exports.safeVaultRelativePath = safeVaultRelativePath;
module.exports.bytesEqual = bytesEqual;
